### ISSUE TITLE
Some gtk-versions over-ride our comment border-lefts

### ISSUE THREAD

**Issue by samdroid-apps** [samdroid-apps/reddit-is-gtk#10]
From thread:  https://www.reddit.com/r/linux/comments/4c7mxe//d1hisaj

![](http://i.imgur.com/5VlXeHV.png)

I don't know what the theme is though.

**Comment by przmkg** [comment]
The theme is Arc and you can find it [here](https://github.com/horst3180/arc-theme) if it is of any help.

**Comment by tgraven** [comment]
I was the one who took the screenshot, and I was still having the same issue even when switching to the default Adwaita theme.

**Comment by samdroid-apps** [comment]
Oh, what Gtk+ version are you using?

`rpm -q gtk3`?

**Comment by samdroid-apps** [comment]
Just tested with the arc theme, it is not an issue with that:

[![https://gyazo.com/42236be059235178681c42c288b681a5](https://i.gyazo.com/42236be059235178681c42c288b681a5.png)](https://gyazo.com/42236be059235178681c42c288b681a5)

So maybe check your gtk version :\

**Comment by tgraven** [comment]
I'm using gtk-3.18.8 in Gentoo Linux.

**Comment by tgraven** [comment]
The indent was working properly with Ubuntu MATE's gtk (I think it was .16) but the colored bit on the side wasn't showing.

**Comment by samdroid-apps** [comment]
Closing.  Probably made obslete by the redesign.  Comments welcome at #21
