### ISSUE TITLE
Dark theme support

### ISSUE THREAD

**Issue by samdroid-apps** [samdroid-apps/reddit-is-gtk#12]
- [ ] Hovering over the buttons in list view -> wrong colour in dark view
- [ ] Read row colour too light
- [ ] Entire comments view

[![https://gyazo.com/f0113d496ee9cd521ef11872cb601057](https://i.gyazo.com/f0113d496ee9cd521ef11872cb601057.png)](https://gyazo.com/f0113d496ee9cd521ef11872cb601057)

**Comment by tgraven** [comment]
removing all lines with gnome-gray in style.css seems to fix this. 

EDIT: To elaborate, the error occurs when the background color is defined but the font color is not. Simply not defining the background color in the first place haven't caused any issues in my case.

**Comment by samdroid-apps** [comment]
Supporting any theme other than light Adwinta is gonna be hard with the new design... maybe it is not a good  idea ... see #21

**Comment by tgraven** [comment]
Oh, ok. I might mess around a bit and see if I can come up with something that looks consistently nice.
