### ISSUE TITLE
`make dist' fails with "No rule to make target 'AUTHORS.in', needed by 'distdir'"

### ISSUE THREAD

**Issue by tgraven** [samdroid-apps/reddit-is-gtk#14]
When trying to run make dist I encountered this issue

**Comment by tgraven** [comment]
I would seem removing AUTHORS.in from EXTRA_DIST in Makefile.am should do the trick.

EDIT: Nevermind. It's not quite that simple. I think including a blank AUTHORS.in in the source tree is what it takes.

**Comment by samdroid-apps** [comment]
Awsone, I think that I fixed it.  If you have more issues with make dist please report them.  IDK how makefiles work, so I'm just learning :P

**Comment by tgraven** [comment]
To be honest, I'm sort of in the same boat :P
