### ISSUE TITLE
Define window title and icon

### ISSUE THREAD

**Issue by tgraven** [samdroid-apps/reddit-is-gtk#17]
Right now the window title and icon are undefined, which results in the title defaulting to reddit-is-gtk and the icon defaulting to a grey box with a question mark (ot whatever your gtk theme sets it to)

**Comment by samdroid-apps** [comment]
I pushed a commit that might help on the icon front:  https://github.com/samdroid-apps/reddit-is-gtk/commit/69fd9ca9d31b76b8e4a8da3073a920d7b9846806

**Comment by tgraven** [comment]
Yep, the icon works, the title still doesn't.

**Comment by samdroid-apps** [comment]
I'm really not sure what the title issue is.  I pass the "title" argument to set the title property of the Gtk window.

What desktop environment are you using?  For some reason, GNOME calls it "reddit-is-gtk".  Are you on GNOME 3 as well?

**Comment by tgraven** [comment]
I alternate between MATE and i3, but the issue is in both.

**Comment by bilelmoussaoui** [comment]
@samdroid-apps I think the issue is a missing `Startup_WM_CLASS`, you should add a `self.set_wm_class('a', 'Something for reddit')` to the main window class, and add a `StartupWMClass=a` in the desktop file

**Comment by samdroid-apps** [comment]
I tested that on my GNOME3.20 desktop, and it didn't cause any changes.  What desktop environment are you running?  What part of the DE does this effect?

**Comment by bilelmoussaoui** [comment]
I don't have the issue on Gnome 3.20 but i think an application should have a WM_CLASS so it can be detected by the desktop manager (like ocmpiz..)

**Comment by samdroid-apps** [comment]
Ah, I should test on one of those compositors.

I thought the bug was refering to the fact that the window title in the GNOME overview is just 'reddit-is-gtk', rather than a proper title ('Something for Reddit').

**Comment by bilelmoussaoui** [comment]
Ah, i can open à PR to fix that if you want

**Comment by samdroid-apps** [comment]
If you have a solution, please send the pull request :)

**Comment by bilelmoussaoui** [comment]
Before i open a PR to fix this, i think that you should add a Gtk.Application first; instead of using the Gtk.Window directly, and inside of the Gtk.Application `__init__` method you can use `GLib.set_application_name("Something for reddit")` This will fix this issue without having to use a WM_CLASS. As you can see here a lot of gnome apps have been ported to use Gtk Application too https://wiki.gnome.org/Initiatives/GnomeGoals/PortToGtkApplication. This might help too https://wiki.gnome.org/HowDoI/GtkApplication

**Comment by samdroid-apps** [comment]
I do have a GtkApplication - it is at the bottom of the main.py file

**Comment by bilelmoussaoui** [comment]
My bad! sorry didn't see that
