### ISSUE TITLE
{subreddit,user}-about.ui require gtk 3.20

### ISSUE THREAD

**Issue by tgraven** [samdroid-apps/reddit-is-gtk#18]
subreddit-about.ui and user-about.ui have their gtk requirement set to 3.20, which is a lot higher than necessary. I can confirm there should no issues with setting it to 3.14

**Comment by samdroid-apps** [comment]
I think that this was a glade bug that set them very high :(  Sorry about that.

I recently updated glade, and now it doesn't seem to add that.

Anyway, I will push a commit to remove these errors.
