### ISSUE TITLE
More whitespace for the list view

### ISSUE THREAD

**Issue by samdroid-apps** [samdroid-apps/reddit-is-gtk#2]
![](https://i.imgur.com/kKMdS7u.png)
vs
![](https://raw.githubusercontent.com/jangernert/feedreader/gh-pages/Screenshot2.png)

The list view definatly needs more structure.  I should make it a gtkbuilder thing that has been obsessed over in glade (rather than the random label thing that is now).

Related thread:  https://www.reddit.com/r/gnome/comments/4c7mqn//d1g46k6

**Comment by jangernert** [comment]
Btw: you can tweak the values (margins, alignment and spacings) of widgets with gtk-inspektor. Makes it much easier to find the right values with not having to recompile all the time and seeing everything change in realtime =)

**Comment by samdroid-apps** [comment]
Awesome.  So far it is looking a little like:

[![https://gyazo.com/d16672137029c3bd431f9a3a1b270c88](https://i.gyazo.com/d16672137029c3bd431f9a3a1b270c88.png)](https://gyazo.com/d16672137029c3bd431f9a3a1b270c88)

But still a few more functionality things to implement.  Comments welcome.
