### ISSUE TITLE
j and k shortcuts are opposite of vim's

### ISSUE THREAD

**Issue by tgraven** [samdroid-apps/reddit-is-gtk#20]
I assume that the`j` and `k` shortcuts are meant as a convenience for vim users, but it's very confusing when you expect `j` to move and `k` to move up, but the opposite happens.

**Comment by samdroid-apps** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Ah, they felt a little weird when I was using them.  I suppose that is why.

On 11 April 2016 9:25:10 AM AEST, Tobias Graven notifications@github.com wrote:

> I assume that the`j` and `k` shortcuts are meant as a convenience for
> vim users, but it's very confusing when you expect `j` to move and `k`
> to move up, but the opposite happens.
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/samdroid-apps/reddit-is-gtk/issues/20

---

Sent from my phone. Please excuse my brevity.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJOBAEBCgA4BQJXCv92MRxTYW0gUC4gKE1vYmlsZSBOZXh1cyA0IEN5YW5vZ2Vu
KSA8c2FtQHNhbS50b2RheT4ACgkQvdyMwXnhrYMRGRAAj98/Fls/8/5eBEyjUAma
R8TSt8Vwer9MV76F0CsL9Nf4PRhy6sWLWD2qe5diTGvlG1XmZSd1rHEbndkLc5M0
qxxoXR0XFDhQv43p5Y51orz44LOZzuUYOQqW97RnN+NX2IvkSL1lsjY0TVn5zl9m
60kJ4sLcAc0tY4pfBjqLDKu78YgLYNl3RQUuRE1C+Ss8G+NH5zXIQ+iyGy0ZNlgT
EO82t0fbTCGbG6MciIKm4l26SlO5ttoKb+aC313nEbu4Ul4w0ETfEPo7BytH2ThF
g/ARDg8EWO07CYu42cj1NPCbIOERc7SvfFv4dvR+Pxci+D2hDNqDPom5kVXDcclM
pDpyTJrsTX5N1lAiKvWKAFKWU4ZE9COeK5TZgskgMhpzma1UT0w9CU9wyc7lzqpP
Gj73FtUYfv245FsoIgJapT0fJhjdyOHgguMpVq5zHG9QIeAOdRisn4BXM6hNf9fb
zX58nmWhoHIgfMiyLiitHIdZCbZHlH1CDANi/rG3Q+7wKRXAG8YFC/I7uWiXQjX/
GYmNSHL1xEjP2VlMI2E9h9pyJ4nOrqGgy6AYzC6Hm6dF31RRJF0tJ9A6gxqZHmsJ
qKlxhvn6Az5wemOuCxidMLsfKZmWPaWnQzl5TmksKFFusfbhV9eqe4onCkHIjdxO
OgkPiytYBZc7Jbmc2V5/H3w=
=CYgA
-----END PGP SIGNATURE-----
