### ISSUE TITLE
Comments view - what should it be

### ISSUE THREAD

**Issue by samdroid-apps** [samdroid-apps/reddit-is-gtk#21]
Old:

![https://camo.githubusercontent.com/f1b0804c0a0eb52bb0aa17f9d01c9bd0f48daa61/687474703a2f2f692e696d6775722e636f6d2f70563865486b702e706e67](https://camo.githubusercontent.com/f1b0804c0a0eb52bb0aa17f9d01c9bd0f48daa61/687474703a2f2f692e696d6775722e636f6d2f70563865486b702e706e67)

New:

[![https://gyazo.com/c02f398626dfe834e7c10f87978d1d18](https://i.gyazo.com/c02f398626dfe834e7c10f87978d1d18.png)](https://gyazo.com/c02f398626dfe834e7c10f87978d1d18)

This is a design discussion.  Ideas appreciated.

**Comment by tgraven** [comment]
Some of dark theme issues still remain, but could be fixed by manually defining the font color as black.

**Comment by samdroid-apps** [comment]
Hum.  I will investigate if I can have a dark theme for the application css - as it would make more sense to have dark comment backgrounds.

**Comment by tgraven** [comment]
Maybe sticking to operators like darker() to adjust background colors would work.

**Comment by samdroid-apps** [comment]
I also used this nice tango table:  http://emilis.info/other/extended_tango/

But the issue that I'm facing now is that I have no idea how to detect the dark variant.  I can't see a way to do that via css or python.  But there must be some way!

**Comment by brunelli** [comment]
> But the issue that I'm facing now is that I have no idea how to detect the dark variant

```
settings = Gtk.Settings.get_default()
using_dark_variant = settings.get_property("gtk-application-prefer-dark-theme")
```

**Comment by samdroid-apps** [comment]
Thanks @brunelli, I just merged a commit that made use of that.  We still need to actually write the css for the dark theme, I currently only change the value of $gnome-grey.  Contributions always welcome.
