### ISSUE TITLE
Move add account to shell menu

### ISSUE THREAD

**Issue by bilelmoussaoui** [samdroid-apps/reddit-is-gtk#33]
I think that the add new Account should be moved to gnome shell menu as it looks better there.
And maybe using `Gio.Menu` as model for the popovers. and adding a `width_request` to the popover itself so it can looks better that it does right now. 

I can push a PR to fix this if you want :)

**Comment by samdroid-apps** [comment]
Moving it into the appmenu sounds good.  I don't know enought about GioMenus to do it.  I'm always happy to get patches :)

You are right, the palette looks disgusting.  I really would prefer the list view to look like the lists do in gnome settings, but I haven't drilled into that.

Another idea is to fix up the list view and move the button to be part of the url bar.  That would probably be useful if we ever add hackernews/etc support.

**Comment by bilelmoussaoui** [comment]
I will open a PR later today to fix this then :+1:

**Comment by bilelmoussaoui** [comment]
@samdroid-apps Are you okay if i move the whole account stuff to the Gio.Menu the same way it's done with corebird?

**Comment by samdroid-apps** [comment]
Sounds fine to me.

**Comment by bilelmoussaoui** [comment]
Just a quick update : 
![capture d ecran de 2016-06-21 14-43-37](https://cloud.githubusercontent.com/assets/7660997/16229790/a10633a6-37be-11e6-87d4-b69cde005f36.png)

And btw, i don't know why but the result of this `get_identity_controller().loop_names_ids_tuple()` is a `None`. What i'm missing ? :)

**Comment by samdroid-apps** [comment]
`get_identity_controller().loop_names_ids_tuple()` can return None if there is no accounts added, otherwise it returns an iterator.

**Comment by bilelmoussaoui** [comment]
@samdroid-apps Do you still want me to follow my idea or follow the mockup provided here #38 ? I can have this finished for tomorrow or this evening.

**Comment by samdroid-apps** [comment]
Let's go with the new mockups for now.

**Comment by bilelmoussaoui** [comment]
Alright! I'm going to ping once i start working on anything so we won't work on the same thing.

**Comment by samdroid-apps** [comment]
I don't have much time to work on reddit now, so feel free to send anything!
