### ISSUE TITLE
Add a static bundle

### ISSUE THREAD

**Issue by samdroid-apps** [samdroid-apps/reddit-is-gtk#35]
Some people like the static packaging trend, like flatpack.  I'm not a fan, but maybe something for reddit should have a flatpack.

https://github.com/vrutkovs/flatpak-something-for-reddit

**Comment by sramkrishna** [comment]
Let me know if we can help in some way. (re flatpak)

**Comment by probonopd** [comment]
What is the oldest Ubuntu version this can be built on?

**Comment by samdroid-apps** [comment]
There is now a flatpak, see the README
