### ISSUE TITLE
Change the name of this app

### ISSUE THREAD

**Issue by brunelli** [samdroid-apps/reddit-is-gtk#4]
Last year, Reddit changed the policy for third-party apps naming, and stated that third-party apps couldn't have names starting with "Reddit" anymore.

I couldn't find the relevant part of the license, but you can see that some apps changed their names due to this policy change. One example is "Relay for reddit" ([previously Redddit News](https://www.reddit.com/r/reddit_news/comments/3041j0/the_official_reddit_news_renaming_thread/)).

**Comment by samdroid-apps** [comment]
Awesome, I saw this comment argument on /r/linux.  I will send an email to `licensing@reddit.com` and ask their opinion about what is acceptable.

**Comment by tgraven** [comment]
Are there any news on this subject?

**Comment by samdroid-apps** [comment]
They haven't emailed me back.  I'll send them a ping email

**Comment by samdroid-apps** [comment]
Still haven't gotten back to me :(

I will close the issue thread on GitHub.  If they get back to me before GitHub falls out of fashion of goes bankrupt, I will re-open this issue.

Here is the paper trail:

[![https://gyazo.com/e98978d70ecec4f0537270bcc97ced73](https://i.gyazo.com/e98978d70ecec4f0537270bcc97ced73.png)](https://gyazo.com/e98978d70ecec4f0537270bcc97ced73)

**Comment by samdroid-apps** [comment]
Sorry, I was afk for a few days.  But I got an update on this on April the 13th:

> Michael Pope (Reddit Support)
> Apr 12, 10:24
> 
> Hi Sam,
> 
> Very sorry for the delay in answering your question. Congratulations on the application! Unfortunately the name 'Reddit is Gtk+" isn't compliant with the use of our trademark. Assuming you are using our API you can view the terms of use here: https://docs.google.com/a/reddit.com/forms/d/1ao_gme8e_xfZ41q4QymFqg5HD29HggOD8I9-MFTG7So/viewform
> 
> More specifically please view section 4 subsection B, which will answer your question. You may use Reddit in the name as long as the word "for" comes before it. So for example "Gtk+ for Reddit" would be an acceptable name. I hope this helps, and feel free to respond with any other questions you might have. Thank you!

So, the new name is "Something for Reddit".  The repository will be moved shortly and I will change the references in the code.

If you have a suggestion for a better name, that's welcome.
