### ISSUE TITLE
Remove python2 dependencies

### ISSUE THREAD

**Issue by Dragnucs** [samdroid-apps/reddit-is-gtk#42]
Python 2 is too old now and most distributions now come with python 3 by default. Especially fedora and Arch, the only two distros supported at the moment.

Having a clean Parabola installation, it tears my heart to have to install pyhon2 that I haven't had to install for quit a time now.

So please migrate to python 3.

**Comment by samdroid-apps** [comment]
This app is written in python3... What are these python 2 deps?

**Comment by samdroid-apps** [comment]
There are definatly no python 2 deps.

**Comment by Dragnucs** [comment]
The ones pulled by [python-arrow](https://aur.archlinux.org/packages/python-arrow/). Maybe avoiding this package would be better.

**Comment by samdroid-apps** [comment]
That must be an issue with the arch package.  Can you patch that?

**Comment by Dragnucs** [comment]
Probably, I will give it a tray. On my machine, editing the PACKAGEBUILD file to remve the extra dependecies worked fine and could get something-for-reddit running with no python3.

By the way, is ruby-sass itself required or any program that provides the `scss` command is?

**Comment by samdroid-apps** [comment]
Scss is just a build time dependency.  Other programs may work, but I test
against the ruby one.
