### ISSUE TITLE
Window size starts cutting off left and right side of the app

### ISSUE THREAD

**Issue by ElectricPrism** [samdroid-apps/reddit-is-gtk#47]
Window size is wrong on start

![screenshot from 2016-09-12 01-21-39](https://cloud.githubusercontent.com/assets/635971/18429318/89ea4b62-7887-11e6-9b12-fb7e13fef18e.png)

**Comment by samdroid-apps** [comment]
Yuck.  I can easily reproduce this bug.  This is going to be a pain to fix... I'll just chuck the "1.0" milestone on it and come back to it soon.

**Comment by samdroid-apps** [comment]
So two years later I got a different perspective.  It was actually a very easy fix.  Yay!

Turns out, most of the labels have ellipsize turned off (GTK default).  Switching it on made a world of difference.

It will be in the next release.
