### ISSUE TITLE
make fails because of missing style.dark.css

### ISSUE THREAD

**Issue by GuzTech** [samdroid-apps/reddit-is-gtk#48]
Something-for-reddit fails to build because of a (I assume) missing file `style.dark.css` with the following error:

`cp ../data/style.css ../data/style.css.out
make[2]: *** No rule to make target '../data/style.dark.css.out', needed by 'reddit-is-gtk.gresource.c'.  Stop.
`

**Comment by GuzTech** [comment]
I copied style.css and named it style.dark.css just to see if the rest would build, but then I get the following error:

`make[2]: *** No rule to make target '../data/reddit-is-gtk.gresource', needed by 'reddit-is-gtk.gresource.c'.  Stop.`

The closest file that I have is `reddit-is-gtk.gresource.xml`.

EDIT: as with `style.css`, I copied and renamed the xml file, and it did finish building.
However I cannot open any threads, and clicking on the voting arrow as an anonymous user crashes the application. I'm going to try v0.2 as the current master does not seem stable.

**Comment by samdroid-apps** [comment]
Yep, so the "master" branch is the WIP rewrite of the applicaction in Vala to comply with the new UI design.  If you want to browse reddit, use v0.2.  If you want to help develop, use master.

Anyway, this is an issue in my makefile.  I cleaned my builddir and think I have fixes the issues.
