### ISSUE TITLE
Requirements incomplete

### ISSUE THREAD

**Issue by harishr1308** [samdroid-apps/reddit-is-gtk#49]
Two more requirements are required libglib2.0-dev and libgtk2.0-dev
While Executing autogen.sh GLIB_SETTINGS was not recognised.

**Comment by samdroid-apps** [comment]
This app should not require libgtk2.0-dev... it is written in Gtk 3.

I haven't updated the README since I started the move to vala, so any 
patches to update the docs would be appreciated.  It now probably 
requires the "*-devel" version of the Gtk, GLib, Soup and JsonGlib.

**Comment by harishr1308** [comment]
Cool ill make the changes accordingly
