### ISSUE TITLE
Make a COPR Package

### ISSUE THREAD

**Issue by samdroid-apps** [samdroid-apps/reddit-is-gtk#5]
The instructions make no sense, an RPM would help

**Comment by samdroid-apps** [comment]
Started, but still WIP:  https://copr.fedorainfracloud.org/coprs/samtoday/reddit-is-gtk/

**Comment by samdroid-apps** [comment]
I am pretty hopeless at this.  i _might_ give it another shot tomorrow, but really anybody else could do a better job.  Any help is appreciated!!!!!

**Comment by jhasse** [comment]
Have you thought about making a flatpak repo?

**Comment by samdroid-apps** [comment]
So there copr is here:  https://copr.fedorainfracloud.org/coprs/samtoday/something-for-reddit/

@jhasse making a flatpack wasn't on my roadmap.  However, I am happy to take a patch for it.

**Comment by samdroid-apps** [comment]
So there copr is here:  https://copr.fedorainfracloud.org/coprs/samtoday/something-for-reddit/

@jhasse making a flatpack wasn't on my roadmap.  However, I am happy to take a patch for it.

**Comment by jhasse** [comment]
I might look into it :) Thanks for the copr ;)
