### ISSUE TITLE
Syntax Error while running autogen.sh

### ISSUE THREAD

**Issue by harishr1308** [samdroid-apps/reddit-is-gtk#51]
![screenshot from 2016-10-27 16-19-02](https://cloud.githubusercontent.com/assets/8678871/19764673/da9575fc-9c61-11e6-8343-d15c79f84da5.png)

**Comment by aperfeito** [comment]
Hey ..  I have same problem.....  
./configure: line 5558: syntax error near unexpected token `1.42.0'
./configure: line 5558:`GOBJECT_INTROSPECTION_CHECK(1.42.0)

I running Ubuntu 16.04 LTS 
Thanks

**Comment by aperfeito** [comment]
Hey after install GOBJECT_INTROSPECTION package with isn't mach the compile run but give this fails of packages missings
and i need install valac compiler too

checking pkg-config is at least version 0.16... yes
**checking for gobject-introspection... no    CHECK AFTER INSTALL gobject-introspection package.**..
checking for valac... valac
configure: WARNING: no proper vala compiler found
configure: WARNING: you will not be able to compile vala source files
checking whether C compiler accepts -Werror=unknown-warning-option... no
checking whether C compiler accepts -fno-strict-aliasing... yes
checking whether C compiler accepts -Wall... yes
checking whether C compiler accepts -Wextra... yes
checking whether C compiler accepts -Wundef... yes
checking whether C compiler accepts -Wnested-externs... yes
checking whether C compiler accepts -Wwrite-strings... yes
checking whether C compiler accepts -Wpointer-arith... yes
checking whether C compiler accepts -Wmissing-declarations... yes
checking whether C compiler accepts -Wmissing-prototypes... yes
checking whether C compiler accepts -Wstrict-prototypes... yes
checking whether C compiler accepts -Wredundant-decls... yes
checking whether C compiler accepts -Wno-unused-parameter... yes
checking whether C compiler accepts -Wno-missing-field-initializers... yes
checking whether C compiler accepts -Wdeclaration-after-statement... yes
checking whether C compiler accepts -Wformat=2... yes
checking whether C compiler accepts -Wold-style-definition... yes
checking whether C compiler accepts -Wcast-align... yes
checking whether C compiler accepts -Wformat-nonliteral... yes
checking whether C compiler accepts -Wformat-security... yes
checking whether C compiler accepts -Wsign-compare... yes
checking whether C compiler accepts -Wstrict-aliasing... yes
checking whether C compiler accepts -Wshadow... yes
checking whether C compiler accepts -Winline... yes
checking whether C compiler accepts -Wpacked... yes
checking whether C compiler accepts -Wmissing-format-attribute... yes
checking whether C compiler accepts -Wmissing-noreturn... yes
checking whether C compiler accepts -Winit-self... yes
checking whether C compiler accepts -Wredundant-decls... (cached) yes
checking whether C compiler accepts -Wmissing-include-dirs... yes
checking whether C compiler accepts -Wunused-but-set-variable... yes
checking whether C compiler accepts -Warray-bounds... yes
checking whether C compiler accepts -Wimplicit-function-declaration... yes
checking whether C compiler accepts -Wreturn-type... yes
checking whether C compiler accepts -Wswitch-enum... yes
checking whether C compiler accepts -Wswitch-default... yes
checking whether C compiler accepts -Wno-suggest-attribute=format... yes
checking whether C compiler accepts -Wno-error=unused-parameter... yes
checking whether C compiler accepts -Wno-error=missing-field-initializers... yes
checking whether C compiler accepts -Werror=unknown-warning-option... (cached) no
checking whether the linker accepts -Wl,--no-as-needed... yes
checking whether the linker accepts -Wl,--fatal-warnings... yes
checking whether C compiler accepts -std=gnu11... yes
checking for SOMETHING_FOR_REDDIT... no
configure: error: Package requirements (gio-2.0 >= 2.42
                                         libsoup-2.4 >= 2.4
                                         webkit2gtk-4.0 >= 2.0
                                         json-glib-1.0 >= 1.0
                                         gtk+-3.0 >= 3.20) were not met:

No package 'libsoup-2.4' found
No package 'webkit2gtk-4.0' found
No package 'json-glib-1.0' found
No package 'gtk+-3.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SOMETHING_FOR_REDDIT_CFLAGS
and SOMETHING_FOR_REDDIT_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

The question is whats is the library in Ubuntu 16.04 I have to install to compile proprely beside install vlac compiler

**Comment by harishr1308** [comment]
I've fixed the requirements you can try now

**Comment by aperfeito** [comment]
I Try Now after install valac compiler and this was report after in below:
**checking for valac... /usr/bin/valac** _Thats ok but look below the same requests...._
checking whether /usr/bin/valac is at least version 0.32... yes
checking whether C compiler accepts -Werror=unknown-warning-option... no
checking whether C compiler accepts -fno-strict-aliasing... yes
checking whether C compiler accepts -Wall... yes
checking whether C compiler accepts -Wextra... yes
checking whether C compiler accepts -Wundef... yes
checking whether C compiler accepts -Wnested-externs... yes
checking whether C compiler accepts -Wwrite-strings... yes
checking whether C compiler accepts -Wpointer-arith... yes
checking whether C compiler accepts -Wmissing-declarations... yes
checking whether C compiler accepts -Wmissing-prototypes... yes
checking whether C compiler accepts -Wstrict-prototypes... yes
checking whether C compiler accepts -Wredundant-decls... yes
checking whether C compiler accepts -Wno-unused-parameter... yes
checking whether C compiler accepts -Wno-missing-field-initializers... yes
checking whether C compiler accepts -Wdeclaration-after-statement... yes
checking whether C compiler accepts -Wformat=2... yes
checking whether C compiler accepts -Wold-style-definition... yes
checking whether C compiler accepts -Wcast-align... yes
checking whether C compiler accepts -Wformat-nonliteral... yes
checking whether C compiler accepts -Wformat-security... yes
checking whether C compiler accepts -Wsign-compare... yes
checking whether C compiler accepts -Wstrict-aliasing... yes
checking whether C compiler accepts -Wshadow... yes
checking whether C compiler accepts -Winline... yes
checking whether C compiler accepts -Wpacked... yes
checking whether C compiler accepts -Wmissing-format-attribute... yes
checking whether C compiler accepts -Wmissing-noreturn... yes
checking whether C compiler accepts -Winit-self... yes
checking whether C compiler accepts -Wredundant-decls... (cached) yes
checking whether C compiler accepts -Wmissing-include-dirs... yes
checking whether C compiler accepts -Wunused-but-set-variable... yes
checking whether C compiler accepts -Warray-bounds... yes
checking whether C compiler accepts -Wimplicit-function-declaration... yes
checking whether C compiler accepts -Wreturn-type... yes
checking whether C compiler accepts -Wswitch-enum... yes
checking whether C compiler accepts -Wswitch-default... yes
checking whether C compiler accepts -Wno-suggest-attribute=format... yes
checking whether C compiler accepts -Wno-error=unused-parameter... yes
checking whether C compiler accepts -Wno-error=missing-field-initializers... yes
checking whether C compiler accepts -Werror=unknown-warning-option... (cached) no
checking whether the linker accepts -Wl,--no-as-needed... yes
checking whether the linker accepts -Wl,--fatal-warnings... yes
checking whether C compiler accepts -std=gnu11... yes
checking for SOMETHING_FOR_REDDIT... no
configure: error: Package requirements (gio-2.0 >= 2.42
                                         libsoup-2.4 >= 2.4
                                         webkit2gtk-4.0 >= 2.0
                                         json-glib-1.0 >= 1.0
                                         gtk+-3.0 >= 3.20) were not met:

No package 'libsoup-2.4' found
No package 'webkit2gtk-4.0' found
No package 'json-glib-1.0' found
No package 'gtk+-3.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SOMETHING_FOR_REDDIT_CFLAGS
and SOMETHING_FOR_REDDIT_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by aperfeito** [comment]
I saw your document readme and see the requirements and mess up if install GTK 3.22 will be mess up my video drivers with mean the library libcairo etc... I using the library made by  Intel that my video card is. Thanks

**Comment by samdroid-apps** [comment]
Do you have the -devel version of all the packages (`gtk3-devel`, etc)?

**Comment by harishr1308** [comment]
No. I'm Sorry i dont know the corresponding devel versions of those packages
