### ISSUE TITLE
Error  while running make command

### ISSUE THREAD

**Issue by harishr1308** [samdroid-apps/reddit-is-gtk#55]
make  all-recursive
make[1]: Entering directory '/home/harish/Projects/something-for-reddit'
Making all in src
make[2]: Entering directory '/home/harish/Projects/something-for-reddit/src'
  VALAC    something_for_reddit_vala.stamp
/bin/bash: valac: command not found
Makefile:670: recipe for target 'something_for_reddit_vala.stamp' failed
make[2]: *** [something_for_reddit_vala.stamp] Error 127
make[2]: Leaving directory '/home/harish/Projects/something-for-reddit/src'
Makefile:530: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/harish/Projects/something-for-reddit'
Makefile:427: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by julianrichen** [comment]
```
/bin/bash: valac: command not found
```

Do you have `valac` installed?

**Comment by harishr1308** [comment]
No i dont. I'll try that now.

**Comment by harishr1308** [comment]
That resolved one part of the error. Now i've got

make[2]: **\* No rule to make target '../data/style.dark.css.out', needed by 'reddit-is-gtk.gresource.c'.  Stop.
make[2]: Leaving directory '/home/harish/Projects/something-for-reddit/src'
Makefile:530: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/harish/Projects/something-for-reddit'
Makefile:427: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by julianrichen** [comment]
Look at issue #48 

@samdroid-apps is re-writing the application in Vala instead of Python so anything in the master branch may or may not work.

You want to build to build v0.2 for a stable python-based experience:

``` bash
git clone https://github.com/samdroid-apps/something-for-reddit
git checkout tags/v0.2
cd something-for-reddit
./autogen.sh
make
sudo make install
```

Or download the source here:
https://github.com/samdroid-apps/something-for-reddit/releases/tag/v0.2

**Comment by samdroid-apps** [comment]
Hi just catching up on this.  I've gone back to the python release and started to fix some bugs.  Therefore, this build issue should be fixed.

Please consider testing the latest version (from master in the git repo) and reopen the issue if it still doesn't build.
