### ISSUE TITLE
Login Error,  URL cannot be shown

### ISSUE THREAD

**Issue by atbeyi** [samdroid-apps/reddit-is-gtk#58]
when trying to login, after entering credentials the allow and decline screen appears, pressing allow gives  "URL cannot be shown" error.

**Comment by samdroid-apps** [comment]
Hi @atbeyi - are you able to reproduce this bug or provide more information to help me track it down?  I've got a similar report at #61 but I still haven't been able to reproduce it.

What distro?

What webkitgtk+ versions?

Does it work only on specific reddit accounts?

**Comment by samdroid-apps** [comment]
Fixed along with #61!  Yay.  I'll make a new release.
