### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by J316** [samdroid-apps/reddit-is-gtk#61]
When I attempt to login, after I enter user/password and allow the application, I get this error message
`Redirection to URL with a scheme that is not HTTP(S)`
All I can do is close the window. If I attempt to sign in again I have to confirm once more only to find this message again. The account is logged in correctly because if I skip the allow message and go to preference, I can navigate the website from that popup window while signed in.
App version is 0.2, installed through AUR

**Comment by samdroid-apps** [comment]
Huh.  Thanks for reporting it.

I haven't looked at this project for a while.  But I want to get back into it.  So my plan is basically:

- revert the head of the tree to the python version
- fix any build problems
- try and fix this bug

I'll keep you updated!

**Comment by samdroid-apps** [comment]
Huh this is interesting.  I've started with a clean install and it worked fine for me.

I'll try enabling the new reddit mode online... maybe that is required.

Could you give some more details about your environment?

**Comment by samdroid-apps** [comment]
Ok, so I am using the new reddit.  But even then, I just get the old slow and it works fine:


![screenshot from 2018-10-29 15-53-16](https://user-images.githubusercontent.com/6022042/47630072-86e62680-db8a-11e8-8a79-417d1a708f3d.png)
![screenshot from 2018-10-29 15-53-41](https://user-images.githubusercontent.com/6022042/47630071-86e62680-db8a-11e8-88ca-349588bb6721.png)

If yours looks different, can you post that?

**Comment by J316** [comment]
Mine looks exactly like this (I also have a warning about cookie acceptance on the bottom). When I click on 'allow' I get that error message and I can only close the login window, so there's no way I can't sign in.

**Comment by samdroid-apps** [comment]
That's extremely odd.  If you find any steps that help reproduce the bug, that would be really helpful.

If you create a new reddit account for testing, it it reproducible?

**Comment by J316** [comment]
@samdroid-apps Yes. With another account the issue persists. I don't know how to reproduce it since I just installed the application from AUR and the issue is there.
The only possible variable could be that I used the application in the past,  when the name was reddit-gtk, indeed I also tried to revoke authorisation from Reddit account, but the issue persists. I tried to check for old configuration files that may interfere, but I couldn't find any folder related to this app (where are the config files located?), or I simply deleted the configuration folder when I deleted the application some time ago.

**Comment by SaritaHerrera** [comment]
Hi, i have the same problem but after some minutes i found the popup windows don't refresh and send the error : Redirection to URL with a scheme that is not HTTP(S)
But if you right click on that popup and click on reload  voila!  you are login.
Sorry for my English and hope this works for you.

**Comment by samdroid-apps** [comment]
@SaritaHerrera - would you be able to screenshot the popups you are talking about?  That would be really helpful!

**Comment by SaritaHerrera** [comment]
> @SaritaHerrera - would you be able to screenshot the popups you are talking about? That would be really helpful!

After this screen (when you click in allow) the error appears in the same window, you need to right click and select reload and after that you are in... i cant take a screenshot because im login now... :) 

https://user-images.githubusercontent.com/6022042/47630071-86e62680-db8a-11e8-88ca-349588bb6721.png

**Comment by samdroid-apps** [comment]
I was just able to reproduce it when I was signing in inside the flatpak.  This is literally just after I made the release.  Well better late than never.

So this error message is coming from webkit, not reddit.  It seems to be coming from about here: https://gitlab.apertis.org/hmi/webkit-gtk-clutter/commit/412ba0c87651b61101ad5066356df5fd9c4dc0ea

Your workaround makes it all make sense @SaritaHerrera!  It is webkit blocking the load, but reloading allows it to go through.  I will look into changing where it we hook into read the url... and I suppose that can be "the bugfix release... redux!"

Thanks for everybody's patience on this issue!
