### ISSUE TITLE
Error: "Redirection to URL with a scheme that is not HTTP(S)" when logging in

### ISSUE THREAD

**Issue by ghost** [samdroid-apps/reddit-is-gtk#77]
Hi guys,

I'm running up-to-date Manjaro linux, and I installed something-for-reddit from the Arch User Repository via `yay`. The specific version of the [package](https://aur.archlinux.org/packages/something-for-reddit/) is `something-for-reddit 0.2-2`, and I'm running `webkit2gtk 2.22.5-1`

When I try to log into reddit, right after the login screen, I get a plain white error page that says "Redirection to URL with a scheme that is not HTTP(S)."

Not totally sure how to troubleshoot this, if no one else is getting it, I'll try building the package straight from github instead. There's also a something-for-reddit-git package, which may work better, but it has a lower version number (0.1-1).

Much thanks :)

**Comment by ghost** [comment]
Derp, so sorry guys, I didn't realize this was a duplicate. I tried searching for the same issue, but I guess I just missed it. :sadderpyface:

**Comment by ghost** [comment]
Can confirm that the workaround for #61 worked for me. So sorry for the spurious issue.

Cheers guys.

**Comment by samdroid-apps** [comment]
Did it work with the bugfix release?

**Comment by ghost** [comment]
I'm still using the default Arch/Manjaro package, but it worked when I right-clicked and hit refresh.
