### ISSUE TITLE
Fails to run on lower gtk version

### ISSUE THREAD

**Issue by parkerlreed** [samdroid-apps/reddit-is-gtk#8]
reddit-is-gtk compiles fine and installs but when I try to run it, it complains about not having GTK 3.20. I would assume the configure script should error out and not let it compile if that's a hard requirement.

```
[parker@e73 reddit-is-gtk]$ reddit-is-gtk 
sys:1: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.

(reddit-is-gtk:12230): Gtk-WARNING **: Theme parsing error: style.css:38:41: Missing name of pseudo-class

(reddit-is-gtk:12230): Gtk-ERROR **: failed to add UI: .:3:50 Required gtk+ version 3.20, current version is 3.18
Trace/breakpoint trap (core dumped)
```

**Comment by samdroid-apps** [comment]
Glade added a "requires gtk+3.20" statement to the top of the `.ui` files.  I don't know why.

I looked through the files and didn't see anything that should require gtk3.20.  So I made a commit to remove them.

Please `git pull` and try again.  If it gives another error, please post it!

**Comment by parkerlreed** [comment]
It's alive! Thanks for the help.

![1459358940](https://cloud.githubusercontent.com/assets/841440/14151360/81f8548c-f67b-11e5-9a1f-0b4b9519caa2.png)
